name = "chat-app-uss-kinesiologia"
compatibility_date = "2024-01-15"

[env.production]
# Variables de entorno para producción en Cloudflare Pages
# Estas se configuran en el dashboard de Cloudflare Pages
vars = { }

[env.preview]
# Variables de entorno para preview/staging
vars = { }